services:
  hub:
    container_name: selenium-hub
    image: selenium/hub
    networks:
      - grid
    shm_size: 2g
    ports:
      - "4442-4444:4442-4444"

  chrome1:
    container_name: selenium-chrome-node-1
    image: selenium/node-chrome
    networks:
      - grid
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_EVENT_BUS_HOST=selenium-hub
    depends_on:
      - hub

  chrome2:
    container_name: selenium-chrome-node-2
    image: selenium/node-chrome
    networks:
      - grid
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_EVENT_BUS_HOST=selenium-hub
    depends_on:
      - hub

  chrome3:
    container_name: selenium-chrome-node-3
    image: selenium/node-chrome
    networks:
      - grid
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_EVENT_BUS_HOST=selenium-hub
    depends_on:
      - hub

  chrome4:
    container_name: selenium-chrome-node-4
    image: selenium/node-chrome
    networks:
      - grid
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_EVENT_BUS_HOST=selenium-hub
    depends_on:
      - hub

networks:
  grid:
